const Sdata=[
    {   id:1,
        imgsrc:"https://images.wallpapersden.com/image/download/louis-hofmann-and-lisa-vicari-netflix-dark_bGZsa2WUmZqaraWkpJRnZWltrWZmamc.jpg",
                title:'NETFLIX ORIGINAL SERIES ',
                sname:'Dark',
                link:"https://www.netflix.com/pk/title/80100172",
    },
    {   id:2,
        imgsrc:"https://i.pinimg.com/originals/98/3f/fc/983ffcb859f60ab193ee559eb083b00c.png",
        title:'NETFLIX ORIGINAL SERIES ',
        sname:'Extra Curricular ',
        link:"https://www.netflix.com/pk/title/80990668" ,
        
    },
    {   id:3,
        imgsrc:"https://wallpapercave.com/wp/wp1839579.jpg",
        title:'NETFLIX ORIGINAL SERIES',
        sname:'Stranger things',
        link:"https://www.netflix.com/pk/title/80057281",
    },
    {   id:4,
        imgsrc:"https://upload.wikimedia.org/wikipedia/en/b/b9/The_Vampire_Diaries_S8_DVD_Cover.jpg",
            title:'NETFLIX ORIGINAL SERIES ',
            sname:'The Vampire Diaries',
            link:"https://whatsnewonnetflix.com/pakistan/559270/the-vampire-diaries-2017/season-1/episode-1/pilot",
         
    },
    {   id:5,
        imgsrc:"https://www.whats-on-netflix.com/wp-content/uploads/2019/04/My-First-First-Love-Netflix-K-Drama.jpg.webp",
            title:'NETFLIX ORIGINAL SERIES ',
            sname:'My First-2 Love',
            link:"https://www.netflix.com/pk/title/81026700",
    },
];
export default Sdata;